name: Build on Ops, Deploy to App Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    container:
      image: node:18-bullseye

    steps:
      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 步驟 4: 建置 Docker 映像並保存
      - name: Build and save Docker Image
        id: build_image
        run: |
          # 使用 'cut' 命令來截取 SHA
          SHORT_SHA=$(echo $GITEA_SHA | cut -c1-7)
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-${SHORT_SHA}
          IMAGE_NAME=ragforq-app:${IMAGE_TAG}
          
          docker build -t $IMAGE_NAME .
          echo "Image built: $IMAGE_NAME"
          
          # 將映像保存到當前工作目錄的絕對路徑下
          docker save $IMAGE_NAME -o ${GITEA_WORKSPACE}/ragforq-app.tar
          echo "Image saved to ${GITEA_WORKSPACE}/ragforq-app.tar"
          
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITEA_ENV
          echo "IMAGE_PATH=${GITEA_WORKSPACE}/ragforq-app.tar" >> $GITEA_ENV

      # 步驟 5: 部署到應用伺服器
      - name: Deploy to Application Server (.121)
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.100.121
          username: qsiadmin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # 明確指定要傳輸的檔案的絕對路徑
          source: ${{ env.IMAGE_PATH }}
          target: "/home/qsiadmin/"
          script: |
            # 遠程執行的腳本
            cd /home/qsiadmin/
            
            # 確保 tar 包存在
            if [ ! -f "ragforq-app.tar" ]; then
                echo "ERROR: ragforq-app.tar not found on remote server!"
                exit 1
            fi

            echo "Loading Docker image from tarball..."
            docker load < ragforq-app.tar

            CONTAINER_NAME=ragforq-production
            echo "Stopping and removing old container if it exists..."
            if [ $(docker ps -q -f name=$CONTAINER_NAME) ]; then
              docker stop $CONTAINER_NAME
              docker rm $CONTAINER_NAME
            fi

            echo "Preparing data directories..."
            mkdir -p ~/rag_data/db
            mkdir -p ~/rag_data/documents
            mkdir -p ~/.cache/huggingface

            echo "Running new container with image: ${{ env.IMAGE_NAME }}"
            docker run -d \
              --gpus all \
              --restart always \
              --name $CONTAINER_NAME \
              -p 8501:8501 \
              -p 8000:8000 \
              -v ~/rag_data/db:/app/db \
              -v ~/rag_data/documents:/app/documents \
              -v ~/.cache/huggingface:/root/.cache/huggingface \
              ${{ env.IMAGE_NAME }}

            echo "Cleaning up..."
            docker image prune -f
            rm ragforq-app.tar
            echo "Deployment successful!"