name: Build on Ops, Deploy to App Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    container:
      image: node:18-bullseye

    steps:
      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 這是我們修改的地方
      - name: Build and save Docker Image
        id: build_image
        run: |
          # 使用 'cut' 命令來截取 SHA，兼容所有 Shell
          SHORT_SHA=$(echo $GITEA_SHA | cut -c1-7)
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-${SHORT_SHA}
          IMAGE_NAME=ragforq-app:${IMAGE_TAG}
          
          docker build -t $IMAGE_NAME .
          echo "Image built: $IMAGE_NAME"
          
          docker save $IMAGE_NAME -o ragforq-app.tar
          echo "Image saved to ragforq-app.tar"
          
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITEA_ENV

      # 後續的 Deploy to Application Server 步驟保持不變...
      - name: Deploy to Application Server (.121)
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.100.121
          username: qsiadmin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "ragforq-app.tar"
          target: "/home/qsiadmin/"
          script: |
            cd /home/qsiadmin/
            docker load < ragforq-app.tar
            CONTAINER_NAME=ragforq-production
            if [ $(docker ps -q -f name=$CONTAINER_NAME) ]; then
              docker stop $CONTAINER_NAME
              docker rm $CONTAINER_NAME
            fi
            mkdir -p ~/rag_data/db
            mkdir -p ~/rag_data/documents
            mkdir -p ~/.cache/huggingface
            docker run -d \
              --gpus all \
              --name $CONTAINER_NAME \
              -p 8501:8501 \
              -p 8000:8000 \
              -v ~/rag_data/db:/app/db \
              -v ~/rag_data/documents:/app/documents \
              -v ~/.cache/huggingface:/root/.cache/huggingface \
              ${{ env.IMAGE_NAME }}
            docker image prune -f
            rm ragforq-app.tar